import vanilleBourbon from '../assets/glace_vanille_bourbon_sauce_caramel_carre.jpg'
import glaceMenthe from '../assets/glace_menthe_verveine_feuille_menthe_vue_dessus_carre.jpg'
import sorbetCitron from '../assets/sorbet_citron_vert_romarin_batonnet_carre.jpg'
import glaceNoix from '../assets/glace_noix_grenoble_eclats_noix_carre.jpg'
import sorbetCassis from '../assets/sorbet_cassis_batonnet_carre.jpg'
import praline from "../assets/glace_praline_eclats_praline_vue_dessus_carre.jpg"
import cafe from "../assets/glace_cafe_carre.jpg"
import chocolatNoir from "../assets/glace_chocolat_boules_carre.jpg"
import abricot from "../assets/sorbet_abricot_thym_batonnet_carre.jpg"
import myrtille from "../assets/sorbet_myrtille_batonnet_carre.jpg"
import nougat from "../assets/glace_nougat_amandes_effilees_carre.jpg"
import fraise from "../assets/sorbet_fraise_batonnet_glacon_carre.jpg"
import caramel from "../assets/glace_caramel_carre.jpg"
import pistache from "../assets/glace_pistache_eclats_carre.jpg"

export const listeGlaces = [
    {
        name: "Glace vanille de Tahiti, sauce caramel",
        id: "gvb",
        cover: vanilleBourbon,
        categorie: "glace",
        gamme: "classique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "grains naturels de vanille"
        ],
        volume: 750,
        prix: 6,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: false,
        sansLait: false,
        sansOeuf: false,
        sansNoix: true,
    },
    {
        name: "Glace chocolat noir, sauce chocolat",
        id: "gcltn",
        cover: chocolatNoir,
        categorie: "glace",
        gamme: "classique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "poudre de cacao",
            "chocolat noir 70%"
        ],
        volume: 750,
        prix: 6,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: false,
        sansLait: false,
        sansOeuf: false,
        sansNoix: true,
    },
    {
        name: "Glace pistache, éclats de pistaches grillées",
        id: "gptch",
        cover: pistache,
        categorie: "glace",
        gamme: "classique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "PISTACHE"
        ],
        volume: 750,
        prix: 7,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: false,
        nouveaute: false,
        sansLait: false,
        sansOeuf: false,
        sansNoix: false,
    },
    {
        name: "Glace caramel, éclats de caramel et fleur de sel",
        id: "gcfs",
        cover: caramel,
        categorie: "glace",
        gamme: "classique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "caramel",
            "fleur de sel"
        ],
        volume: 750,
        prix: 8,
        enSoldes: true,
        meilleuresVentes: true,
        enStock: true,
        nouveaute: false,
        sansLait: false,
        sansOeuf: false,
        sansNoix: true,
    },
    {
        name: "Glace café, copeaux de chocolat noir 70%",
        id: "gcaf",
        cover: cafe,
        categorie: "glace",
        gamme: "classique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "extrait de café pur Arabica",
            "chocolat noir 70%"
        ],
        volume: 750,
        prix: 6,
        enSoldes: true,
        meilleuresVentes: false,
        enStock: false,
        nouveaute: false,
        sansLait: false,
        sansOeuf: true,
        sansNoix: true,
    },
    {
        name: "Glace nougat de Montélimar, brisures de nougat",
        id: "gngm",
        cover: nougat,
        categorie: "glace",
        gamme: "classique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "AMANDE",
            "miel",
            "nougat (AMANDE)"
        ],
        volume: 750,
        prix: 9,
        enSoldes: false,
        meilleuresVentes: true,
        enStock: false,
        nouveaute: true,
        sansLait: false,
        sansOeuf: false,
        sansNoix: false,
    },
    {
        name: "Glace praline, éclats de praline rose",
        id: "gprl",
        cover: praline,
        categorie: "glace",
        gamme: "saveur locale",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "AMANDE",
            "praline (AMANDE)",
            "sirop de glucose",
            "colorant carmin"
        ],
        volume: 750,
        prix: 10,
        enSoldes: false,
        meilleuresVentes: true,
        enStock: true,
        nouveaute: false,
        sansLait: false,
        sansOeuf: false,
        sansNoix: false,
    },
    {
        name: "Glace noix de Grenoble, éclats de noix torréfiées",
        id: "gngnb",
        cover: glaceNoix,
        categorie: "glace",
        gamme: "saveur locale",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "NOIX de Grenoble"
        ],
        volume: 750,
        prix: 9,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: true,
        sansLait: false,
        sansOeuf: false,
        sansNoix: false,
    },
    {
        name: "Glace menthe et verveine citronnelle",
        id: "gmch",
        cover: glaceMenthe,
        categorie: "glace",
        gamme: "aromatique",
        ingredients: [
            "LAIT",
            "CREME",
            "sucre",
            "OEUF",
            "verveine citronnelle fraîche",
            "menthe fraîche"
        ],
        volume: 750,
        prix: 10,
        enSoldes: true,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: false,
        sansLait: false,
        sansOeuf: false,
        sansNoix: true,
    },
    {
        name: "Sorbet cassis",
        id: "scss",
        cover: sorbetCassis,
        categorie: "sorbet",
        gamme: "classique",
        ingredients: [
            "eau",
            "sucre",
            "purée de cassis"
        ],
        volume: 750,
        prix: 7,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: false,
        sansLait: true,
        sansOeuf: true,
        sansNoix: true,
    },
    {
        name: "Sorbet citron vert romarin",
        id: "sctvb",
        cover: sorbetCitron,
        categorie: "sorbet",
        gamme: "aromatique",
        ingredients: [
            "eau",
            "sucre",
            "purée de citron vert",
            "basilic frais"
        ],
        volume: 750,
        prix: 7,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: false,
        nouveaute: false,
        sansLait: true,
        sansOeuf: true,
        sansNoix: true,
    },
    {
        name: "Sorbet myrtille",
        id: "smrt",
        cover: myrtille,
        categorie: "sorbet",
        gamme: "saveur locale",
        ingredients: [
            "eau",
            "sucre",
            "purée de myrtille",
            "jus de citron"
        ],
        volume: 750,
        prix: 9,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: true,
        sansLait: true,
        sansCreme: true,
        sansOeuf: true,
        sansAmande: true,
        sansNoix: true,
        sansPistache: true
    },
    {
        name: "Sorbet fraise, coulis de fraise",
        id: "sfrs",
        cover: fraise,
        categorie: "sorbet",
        gamme: "classique",
        ingredients: [
            "eau",
            "sucre",
            "fraise",
            "jus de citron",
        ],
        volume: 750,
        prix: 7,
        enSoldes: false,
        meilleuresVentes: false,
        enStock: true,
        nouveaute: false,
        sansLait: true,
        sansOeuf: true,
        sansNoix: true,
    },
    {
        name: "Sorbet abricot thym",
        id: "sath",
        cover: abricot,
        categorie: "sorbet",
        gamme: "aromatique",
        ingredients: [
            "eau",
            "sucre",
            "purée d'abricot",
            "thym frais"
        ],
        volume: 750,
        prix: 10,
        enSoldes: true,
        meilleuresVentes: true,
        enStock: false,
        nouveaute: true,
        sansLait: true,
        sansOeuf: true,
        sansNoix: true,
    },
]

